<?php
define("_DBName","playmob");
define("_DBServer","localhost");
define("_DBUser","play");
define("_DBPassword","play");
define("_DBPort","5432");

define("_SONGPATH","../../files/");//USE RELATIVE PATH BECAUSE THE ABSOLUTE NOT WORK
define("_LIBRARY_PATH","/PlayMob/lib/");

define("_FINDER_PATH","/PlayMob/modules/finder/");
define("_HOME_PATH","/PlayMob/modules/home/");
define("_INDEXER_PATH","/PlayMob/modules/indexer/");
define("_LOGINPATH","/PlayMob/");
define("_CONFIG_PATH","/PlayMob/modules/config/");

define("_HEAD","/PlayMob/modules/shared/head.php");
define("_LOGO","PlayMob: Play Mobility!");

define("_FOOTER",'<h1><img id="logo" title="PlayMob: Play Mobility" src="/PlayMob/logo.png"/> by <a data-ajax="false" target="_blank" href="https://twitter.com/coguetverd">@coguet.verd</a></h1><a class="ui-btn-right" target="_blank" rel="license" href="https://github.com/koolmod/PlayMob"><img alt="Licencia Creative Commons" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png" /></a>');



?>
